############################
### ECILA'S ADVANCED KEYBINDS ###
############################

# vars
$menu = /mnt/prometheus/Dev/Repos/hypr-tofi/build/hypr-tofi -t dracula -e drun
$hmenu = /mnt/prometheus/Dev/Repos/hypr-tofi/build/hypr-tofi

bind = $layer1, Space, exec, $menu
bind = $layer4, Space, exec, $hmenu

# Alt+Tab functionality for window cycling
#bind = ALT, Tab, workspace, e+1
#bind = ALT, Tab, hyprexpo:expo, toggle
bind = ALT SHIFT, Tab, workspace, e-1

# Scroll workspaces with layer4
bind = $layer4, l, workspace, m+1
bind = $layer4, h, workspace, m-1

# Toggle floating
bind = $layer3, F, togglefloating

# Move between workspaces with layer3
bind = $layer3, h, movecurrentworkspacetomonitor, l
bind = $layer3, k, movetoworkspace, r+1
bind = $layer3, j, movetoworkspace, r-1
bind = $layer3, l, movecurrentworkspacetomonitor, r

# tmux menu
bind = $layer2, Space, exec, $tmuxMenu

# Switch workspaces with layer1 + [alphanumeric keys]
bind = $layer1, Q, workspace, name:Q
bind = $layer1, W, workspace, name:Web
bind = $layer1, E, workspace, name:E
bind = $layer1, R, workspace, name:R
bind = $layer1, T, workspace, name:T
bind = $layer1, Y, workspace, name:Y
bind = $layer1, U, workspace, name:U
bind = $layer1, I, workspace, name:I
bind = $layer1, O, workspace, name:O
bind = $layer1, P, workspace, name:P
bind = $layer1, a, workspace, name:A
bind = $layer1, s, workspace, name:S
bind = $layer1, d, workspace, name:D
bind = $layer1, f, workspace, name:F
bind = $layer1, g, workspace, name:G
bind = $layer1, z, workspace, name:Z
bind = $layer1, x, workspace, name:X
bind = $layer1, c, workspace, name:C
bind = $layer1, v, workspace, name:V
bind = $layer1, b, workspace, name:B
bind = $layer1, n, workspace, name:N
bind = $layer1, m, workspace, name:M

# Move active window to a workspace with layer2 + [alphanumeric keys]
bind = $layer2, Q, movetoworkspace, name:Q
bind = $layer2, W, movetoworkspace, name:Web
bind = $layer2, E, movetoworkspace, name:E
bind = $layer2, R, movetoworkspace, name:R
bind = $layer2, T, movetoworkspace, name:T
bind = $layer2, Y, movetoworkspace, name:Y
bind = $layer2, U, movetoworkspace, name:U
bind = $layer2, I, movetoworkspace, name:I
bind = $layer2, O, movetoworkspace, name:O
bind = $layer2, P, movetoworkspace, name:P
bind = $layer2, a, movetoworkspace, name:A
bind = $layer2, s, movetoworkspace, name:S
bind = $layer2, d, movetoworkspace, name:D
bind = $layer2, f, movetoworkspace, name:F
bind = $layer2, g, movetoworkspace, name:G
bind = $layer2, z, movetoworkspace, name:Z
bind = $layer2, x, movetoworkspace, name:X
bind = $layer2, c, movetoworkspace, name:C
bind = $layer2, v, movetoworkspace, name:V
bind = $layer2, b, movetoworkspace, name:B
bind = $layer2, n, movetoworkspace, name:N
bind = $layer2, m, movetoworkspace, name:M

# Special workspace
bind = $layer3, c, movetoworkspace, special
bind = $layer3, s, togglespecialworkspace

# Monitor brightness (ddcutil)
bindel = $layer2, F11, exec, /home/ecila/.config/hypr/scripts/mon-bright-hyprctl.sh increase 10
bindel = $layer2, F10, exec, /home/ecila/.config/hypr/scripts/mon-bright-hyprctl.sh decrease 10

# Fullscreen variants
bindel = $layer3, F11, fullscreen, 0
bindel = $layer3, M, fullscreen, 1
bindel = $layer3, N, fullscreen, 0
