############################
### GLOBAL KEYBINDINGS    ###
############################

# Variables
$tmuxMenu = /mnt/prometheus/Dev/Repos/hypr-tofi/build/hypr-tofi -p tmux-freeze,tmux-unfreeze,tmux-cold-storage

# Window management
bindm = $layer1, mouse:272, movewindow
bindm = $layer1, mouse:273, resizewindow
bind = $layer1, Backspace, killactive,
bind = $layer1, return, exec, $terminal

# Move focus with layer1 + hjkl (vim) and arrow keys
bind = $layer1, h, movefocus, l
bind = $layer1, k, movefocus, u
bind = $layer1, j, movefocus, d
bind = $layer1, l, movefocus, r
bind = $layer1, left, movefocus, l
bind = $layer1, right, movefocus, r
bind = $layer1, up, movefocus, u
bind = $layer1, down, movefocus, d

# Move windows with layer2 + hjkl (vim) and arrow keys
bind = $layer2, h, movewindow, l
bind = $layer2, k, movewindow, u
bind = $layer2, j, movewindow, d
bind = $layer2, l, movewindow, r
bind = $layer2, left, movewindow, l
bind = $layer2, right, movewindow, r
bind = $layer2, up, movewindow, u
bind = $layer2, down, movewindow, d

# Switch workspaces with layer1 + [0-9]
bind = $layer1, 1, workspace, 1
bind = $layer1, 2, workspace, 2
bind = $layer1, 3, workspace, 3
bind = $layer1, 4, workspace, 4
bind = $layer1, 5, workspace, 5
bind = $layer1, 6, workspace, 6
bind = $layer1, 7, workspace, 7
bind = $layer1, 8, workspace, 8
bind = $layer1, 9, workspace, 9
bind = $layer1, 0, workspace, 0

# Move active window to a workspace with layer2 + [0-9]
bind = $layer2, 1, movetoworkspace, 1
bind = $layer2, 2, movetoworkspace, 2
bind = $layer2, 3, movetoworkspace, 3
bind = $layer2, 4, movetoworkspace, 4
bind = $layer2, 5, movetoworkspace, 5
bind = $layer2, 6, movetoworkspace, 6
bind = $layer2, 7, movetoworkspace, 7
bind = $layer2, 8, movetoworkspace, 8
bind = $layer2, 9, movetoworkspace, 9
bind = $layer2, 0, movetoworkspace, 0

# Scroll through existing workspaces with mainMod + scroll
bind = $layer1, mouse_down, workspace, m+1
bind = $layer1, mouse_up, workspace, m-1

# Volume
bind = , XF86AudioRaiseVolume, exec, amixer -q sset PCM 5%+
bind = , XF86AudioLowerVolume, exec, amixer -q sset PCM 5%-
bind = , XF86AudioMute, exec, amixer -q sset PCM toggle
bind = $layer1, F6, exec, amixer -q sset PCM 5%+
bind = $layer1, F5, exec, amixer -q sset PCM 5%-
bind = $layer1, F7, exec, amixer -q sset PCM toggle

# Laptop multimedia keys for volume
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = $layer1, F11, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = $layer1, F10, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = $layer1, F9, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Screenshots
bind = $layer1, Print , exec, hyprshot -m output -r -z --clipboard-only | satty -c ~/.config/satty/config.toml -o $HOME/Media/Screenshots/%Y-%m-%d_%H:%M:%S.png -f -
bind = $layer2, Print , exec, hyprshot -m region -r -z --clipboard-only | satty -c ~/.config/satty/config.toml -o $HOME/Media/Screenshots/%Y-%m-%d_%H:%M:%S.png -f -
