############################
### PAT'S KEYBINDINGS    ###
############################

# vars
$menu = /mnt/prometheus/Dev/Repos/hypr-tofi/build/hypr-tofi -t cherry-blossom -e drun
$hmenu = /mnt/prometheus/Dev/Repos/hypr-tofi/build/hypr-tofi -t cherry-blossom

bind = $layer1, Space, exec, $menu
bind = $layer4, Space, exec, $hmenu

# Example: Super+B opens Brave browser
bind = $layer1, B, exec, brave
