-- Generated by Noctalia

local primary = "rgb(c7a1d8)"
local surface = "rgb(1c1822)"
local secondary = "rgb(a984c4)"
local error = "rgb(e9899d)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
